version: '3.8'

services:
  pipeline_disaster_tweet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: disaster-tweet-pipeline
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
    command: python src/pipeline_tweet_classifier.py