version: '3.8'

services:
  disaster_tweet_cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: disaster-tweet-cli
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    command: python main.py